src/com/shop_order/model/InsertOrder.java
package com.shop_order.model;

import java.util.Random;

import com.order_detail.model.Order_detailJDBCDAO;
import com.order_detail.model.Order_detailVO;

public class InsertOrder {
	public static void main(String[] args) {
		String address[] = new String[6];
		address[0] = "台北市中正區重慶南路一段122號";
		address[1] = "台中市西屯區四川東街33號 ";
		address[2] = "台南市中西區萬昌街15號";
		address[3] = "高雄市鼓山區大順一路459號";
		address[4] = "高雄市三民區慶雲街105號";
		address[5] = "桃園市中壢區中山路123號";

		int i=1;

		for(int b=0;b<=5;b++) {
			Shop_orderJDBCDAO dao = new Shop_orderJDBCDAO();
			Shop_orderVO vo = new Shop_orderVO();
			String b2=(b+1)+"";
				vo.setMember_id("81000"+b2);
				vo.setOrder_status(0);
				vo.setTotal(9999);
				vo.setPay_type(1);
				vo.setDv_address(address[i-1]);
				dao.insert(vo, null);
				///先產生一筆訂單
				Random r = new Random();
				int a = r.nextInt(3)+1;
				InsertOrder.buy(a, vo);
	i++;
		}
		System.out.println("希望筆數OK");
		
	}
	
	
	public static Order_detailVO buy(int a,Shop_orderVO vo) {
		
		
		
		
		Shop_orderJDBCDAO dao = new Shop_orderJDBCDAO();
		Order_detailJDBCDAO orderdao=new Order_detailJDBCDAO();
	
		int p=0;
		
		Integer total=0;
		Order_detailVO ordervo=new Order_detailVO();
		for(int i=0;i<a;i++) {
			Random r = new Random();
			int r2 = r.nextInt(20)+1;
			String po=null;
			p+=r2;
			if(p<10) {
				po="0"+p;
			}
			else {
				po=p+"";
			}
			
			int i2 = r.nextInt(3)+1;
			String productid="3200"+po;
			ordervo.setorder_no(dao.getfresh());
			ordervo.setProduct_id(productid);
			ordervo.setPrice(orderdao.getprice(productid));
			ordervo.setQuantity(i2);
			//明細送出
			orderdao.insert(ordervo, null);
			
			//計算剛剛商品的總金額
			Integer pto=(ordervo.getQuantity())*(ordervo.getPrice());
			//資料送入新增商城訂單
			total+=pto;
			p+=i2;
		}
		
		vo.setTotal(total);
		vo.setOrder_no(dao.getfresh());
		dao.updatetotal(vo);
		return ordervo;
		
	}

}

src/com/shop_order/model/Shop_orderDAO.java
package com.shop_order.model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.List;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

import com.order_detail.model.Order_detailJDBCDAO;
import com.order_detail.model.Order_detailVO;


public class Shop_orderDAO implements Shop_orderDAO_interface{
	private static final String INSERT_STMT =
			"		INSERT INTO SHOP_ORDER (order_no,member_id,order_status,total,pay_type,dv_address) VALUES ('OR-'||to_CHAR(current_timestamp,'YYYY-MM-DD')||'-'||LPAD(to_char(SQ_ORDER_NO.NEXTVAL),6,'0'),?,? ,?, ?, ?)";
		
	private static final String GET_ALL_STMT = 
		"SELECT order_no,member_id,order_status,order_time,total,pay_type,dv_address FROM SHOP_ORDER order by ORDER_NO";
	private static final String GET_ONE_STMT = 
		"SELECT order_no,member_id,order_status,order_time,total,pay_type,dv_address FROM SHOP_ORDER where ORDER_NO = ?";
	private static final String DELETE = 
		"DELETE FROM SHOP_ORDER where order_no = ? ";
	private static final String UPDATE = 
		"UPDATE SHOP_ORDER set order_status=?,dv_address=? where order_no = ?";
	private static final String UPDATESTATUS = 
			"UPDATE SHOP_ORDER set order_status=? where order_no = ?";
	private static final String UPDATETOTAL = 
			"UPDATE SHOP_ORDER set  total=? where order_no = ?";
	private static final String GetFRESH="select   order_no FROM shop_order  WHERE rownum = 1  ORDER BY order_no DESC";
	private static final String GET_ONE_STMT_BYORDER = 
			"SELECT order_no,member_id,order_status,order_time,total,pay_type,dv_address FROM SHOP_ORDER where member_id = ?";
	private static DataSource ds = null;
	static {
		try {
			Context ctx = new InitialContext();
			ds = (DataSource) ctx.lookup("java:comp/env/jdbc/DA106G4");
		} catch (NamingException e) {
			e.printStackTrace();
		}
	}
	
	public String getfresh() {
		String no=null;
		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		 Shop_orderVO  shop_ordervo= null;


		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(GetFRESH);
			    pstmt.executeUpdate();
				rs = pstmt.executeQuery();
				shop_ordervo=new Shop_orderVO();
				while (rs.next()) {
					shop_ordervo.setOrder_no(rs.getString("order_no"));

					
				}
				no=shop_ordervo.getOrder_no();
			// Handle any SQL errors
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return no;
		
		
		
		

	}
	
	
	public void updatetotal(Shop_orderVO shop_ordervo) {
		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();

			pstmt = con.prepareStatement(UPDATETOTAL);
			
	            pstmt.setInt(1, shop_ordervo.getTotal());
	            pstmt.setString(2, shop_ordervo.getOrder_no());
			    pstmt.executeUpdate();

			// Handle any SQL errors
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		
	}
	

	
	@Override
	public void insert(Shop_orderVO shop_ordervo,List<Order_detailVO>list) {
		 Connection con = null;
	        PreparedStatement pstmt = null;

	        try {
				con = ds.getConnection();

				con.setAutoCommit(false);
				String cols[] = {"order_no"};
				pstmt = con.prepareStatement(INSERT_STMT,cols);
	            pstmt.setString(1, shop_ordervo.getMember_id());
	            pstmt.setInt(2, shop_ordervo.getOrder_status());
	            pstmt.setInt(3, shop_ordervo.getTotal());
	            pstmt.setInt(4, shop_ordervo.getPay_type());
	            pstmt.setString(5, shop_ordervo.getDv_address());
	            pstmt.executeUpdate();
	            String next_order_no=null;
				ResultSet rs = pstmt.getGeneratedKeys();

				if (rs.next()) {
					next_order_no = rs.getString(1);
					System.out.println("自增主鍵值= " + next_order_no );
				} else {
					System.out.println("未取得自增主鍵值");
				}
				rs.close();
				
	            //新增訂單明細
				Order_detailJDBCDAO dao=new Order_detailJDBCDAO();
				System.out.println("list.size()-A="+list.size());
				int ii=1;
				for (Order_detailVO detail : list) {
					
					System.out.println("新增開始"+ii);
				detail.setorder_no(next_order_no);
				dao.insert(detail,con);
				ii++;
					
				}
				con.commit();
				con.setAutoCommit(true);
				System.out.println("list.size()-B="+list.size());
				System.out.println("新增部門編號" + next_order_no + list.size()
						+ "明細同時被新增");
	            
	            
	            
	            
	            
	            
	        } catch (SQLException se) {
				if (con != null) {
					try {
						// 3●設定於當有exception發生時之catch區塊內
						System.err.print("Transaction is being ");
						System.err.println("rolled back-由-dept");
						con.rollback();
					} catch (SQLException excep) {
						throw new RuntimeException("rollback error occured. "
								+ excep.getMessage());
					}
				}
				throw new RuntimeException("A database error occured. "
						+ se.getMessage());
				// Clean up JDBC resources
			} finally {
	            if (pstmt != null) {
	                try {
	                    pstmt.close();
	                } catch (SQLException se) {
	                    se.printStackTrace(System.err);
	                }
	            }
	            if (con != null) {
	                try {
	                    con.close();
	                } catch (Exception e) {
	                    e.printStackTrace(System.err);
	                }
	            }
	        }
	}
	@Override
	public void update(Shop_orderVO shop_ordervo) {
		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();

			pstmt = con.prepareStatement(UPDATE);
			
	            pstmt.setInt(1, shop_ordervo.getOrder_status());  
	            pstmt.setString(2, shop_ordervo.getDv_address());
	            pstmt.setString(3, shop_ordervo.getOrder_no());
			    pstmt.executeUpdate();

			// Handle any SQL errors
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		
	}
	@Override
	public void delete(String order_no) {
		// TODO Auto-generated method stub
		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();

			pstmt = con.prepareStatement(DELETE);
			pstmt.setString(1,order_no);
			pstmt.executeUpdate();

		} catch (SQLException se) {
			throw new RuntimeException("並未刪除 "+ se.getMessage());
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		
	}
	@Override
	public Shop_orderVO findByPrimaryKey(String order_no) {
		// TODO Auto-generated method stub
		Shop_orderVO shop_ordervo = null;
		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {
			con = ds.getConnection();

			pstmt = con.prepareStatement(GET_ONE_STMT);
			pstmt.setString(1, order_no);
			rs = pstmt.executeQuery();

			while (rs.next()) {
				shop_ordervo = new Shop_orderVO();
				shop_ordervo.setOrder_no(rs.getString("order_no"));
				shop_ordervo.setMember_id(rs.getString("member_id"));
				shop_ordervo.setOrder_status(rs.getInt("order_status"));
				shop_ordervo.setOrder_time(rs.getTimestamp("order_time"));
				shop_ordervo.setTotal(rs.getInt("total"));
				shop_ordervo.setPay_type(rs.getInt("pay_type"));
				shop_ordervo.setDv_address(rs.getString("dv_address"));

			}	
			// Handle any driver errors
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return shop_ordervo;
	}
	@Override
	public List<Shop_orderVO> getAll() {
		// TODO Auto-generated method stub
		List<Shop_orderVO> list = new ArrayList<Shop_orderVO>();
		 Shop_orderVO  shop_ordervo= null;

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {
			con = ds.getConnection();

			pstmt = con.prepareStatement(GET_ALL_STMT);
			rs = pstmt.executeQuery();

			while (rs.next()) {
				shop_ordervo = new Shop_orderVO();
				shop_ordervo.setOrder_no(rs.getString("order_no"));
				shop_ordervo.setMember_id(rs.getString("member_id"));
				shop_ordervo.setOrder_status(rs.getInt("order_status"));
				shop_ordervo.setOrder_time(rs.getTimestamp("order_time"));
				shop_ordervo.setTotal(rs.getInt("total"));

src/com/shop_order/model/Shop_orderDAO_interface.java
package com.shop_order.model;

import java.util.*;

import com.order_detail.model.Order_detailVO;

public interface Shop_orderDAO_interface {
    public void insert(Shop_orderVO shop_ordervo,List<Order_detailVO>list);
    public void update(Shop_orderVO shop_ordervo);
    public void delete(String order_no);
    public Shop_orderVO findByPrimaryKey(String order_no);
    public List<Shop_orderVO> getAll();
    public List<Shop_orderVO> getOrderBYMEMBER(String member_id);
    public void updatetotal(Shop_orderVO shop_ordervo);
    public void changestatus(Shop_orderVO shop_ordervo);

}

src/com/shop_order/model/Shop_orderVO.java
package com.shop_order.model;

import java.sql.Timestamp;

public class Shop_orderVO implements java.io.Serializable{
   private String order_no;
   private String member_id;
   private Integer order_status;
   private Timestamp order_time;
   private Integer total;   
   private Integer pay_type;
   private String dv_address;

   public Shop_orderVO() {
   }

   public Shop_orderVO(String order_no, String member_id, Integer order_status, Timestamp order_time, Integer total, Integer pay_type, String dv_address) {
      this.order_no = order_no;
      this.member_id = member_id;
      this.order_status = order_status;
      this.order_time = order_time;
      this.total = total;
      this.pay_type = pay_type;
      this.dv_address = dv_address;
   }

   public String getOrder_no() {
      return order_no;
   }

   public void setOrder_no(String order_no) {
      this.order_no = order_no;
   }

   public String getMember_id() {
      return member_id;
   }

   public void setMember_id(String member_id) {
      this.member_id = member_id;
   }

   public Integer getOrder_status() {
      return order_status;
   }

   public void setOrder_status(Integer order_status) {
      this.order_status = order_status;
   }

   public Timestamp getOrder_time() {
      return order_time;
   }

   public void setOrder_time(Timestamp timestamp) {
      this.order_time = timestamp;
   }

   public Integer getTotal() {
      return total;
   }

   public void setTotal(Integer total) {
      this.total = total;
   }

   public Integer getPay_type() {
      return pay_type;
   }

   public void setPay_type(Integer pay_type) {
      this.pay_type = pay_type;
   }

   public String getDv_address() {
      return dv_address;
   }

   public void setDv_address(String dv_address) {
      this.dv_address = dv_address;
   }

@Override
public String toString() {
	return "Shop_orderVO [order_no=" + order_no + ", member_id=" + member_id + ", order_status=" + order_status
			+ ", order_time=" + order_time + ", total=" + total + ", pay_type=" + pay_type + ", dv_address="
			+ dv_address + "]";
}
   
}

WebContent/back-end/shop_order/UpateOrderAddress.jsp
<%@page import="android.com.instant_delivery_order.model.OrderProductVO"%>
<%@ page language="java" contentType="text/html; charset=UTF-8 "
    pageEncoding="UTF-8"%>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
    <%@ page import="com.shop_order.model.*" %>
    
    
   
  
    <%@ page import="java.util.*" %>
    <%Shop_orderVO ordvo=(Shop_orderVO)request.getAttribute("ordvo"); %>
<!DOCTYPE html>
<html>
<head>

 <script src="<%=request.getContextPath() %>/plugin/jquery.twzipcode.min.js"></script>




<style>
input{
    border-radius: 50px;
}

  table#table-1 {
	background-color: #CCCCFF;
    border: 2px solid black;
    text-align: center;
  }
  table#table-1 h4 {
    color: red;
    display: block;
    margin-bottom: 1px;
  }
  h4 {
    color: blue;
    display: inline;
  }
</style>

<style>
  table {
	width: 450px;
	background-color: white;
	margin-top: 1px;
	margin-bottom: 1px;
  }
  table, th, td {
    border: 0px solid #CCCCFF;
  }
  th, td {
    padding: 1px;
  }
</style>

<meta charset="UTF-8">
<title>更新地址</title>
</head>
<body>





		

 <%-- 錯誤表列 --%>
<c:if test="${not empty errorMsgs}">
	<font style="color:red">請修正以下錯誤:</font>
	<ul>
	    <c:forEach var="message" items="${errorMsgs}">
			<li style="color:red">${message}</li>
		</c:forEach>
	</ul>
</c:if>

<FORM METHOD="post" ACTION="OrderServlet.do" name="upateform" id="upateform">
<table>
	<tr>
		<td>訂單編號:<font color=red><b>*</b></font></td>
		
		<td>${ordvo.order_no}</td>
		
	</tr>
	<tr>
		<td>會員編號:<font color=red><b>*</b></font></td>
		<td>${ordvo.member_id}</td>

	</tr>
	<tr>
		<%
    Map<Integer, String> pay_typemap = new HashMap<>();
						pay_typemap.put(0, "點數");
						pay_typemap.put(1, "信用卡");
%>
<c:set var="pay_typemap" value="<%=pay_typemap %>"/>
		<td>訂單狀態:</td>
	<td>	${pay_typemap[ordvo.pay_type]} 
	
	</td>
	</tr>
		<tr>
		<td>訂單生成日期:<font color=red><b>*</b></font></td>
		<td>${ ordvo.order_time}</td>
	</tr>
			<tr>
					<%
    Map<Integer, String> Order_statusmap = new HashMap<>();
		Order_statusmap.put(0, "已成立");
		Order_statusmap.put(1, "運送中");
		Order_statusmap.put(0, "已完成");
		Order_statusmap.put(1, "取消訂單");
%>

<c:set var="Order_statusmap" value="<%=Order_statusmap %>"/>

		<td>付款方式：	</td>
				<td>${Order_statusmap[ordvo.order_status]}</td>
		
		
	
	
	
	
	</tr>
	
	
<tr>
		<td>訂單地址:</td>
		
		<td> <div id="zipcode3">
<div class="address1" data-role="county">
</div>
<div class="address2" data-role="district">
</div>
<%
String city="";
String town="";
String address3="";
int addressstr=ordvo.getDv_address().indexOf("/");
if(addressstr == -1){	
}
else{
	String address[]=ordvo.getDv_address().split("/");
	 city=address[0];
	 town=address[1];
	 address3=address[2];	
	
}
%>

</div>
<input class="address3" name="dv_address" type="text" class="f13 address form-control" value="<%=(address3=="")?ordvo.getDv_address():address3%>">
		



		
		<input type="hidden" name="action" value="OrderUpdate">
<input type="hidden" name="order_no" value="<%=ordvo.getOrder_no()%>">
<input type="hidden" name="member_id" value="<%=ordvo.getMember_id() %>">
<input type="hidden" name="total" value="<%=ordvo.getTotal()%>">
<input type="hidden" name="pay_type" value="<%=ordvo.getPay_type()%>">
<input type="hidden" name="order_status" value="${ ordvo.order_status}">
<input type="hidden" name="address1" id="address1">
<input type="hidden" name="address2" id="address2" >
<input  type="submit" value="送出修改" id="send" name="send">


                                                 <input  type="hidden" name="Order_statusPage" value="${Order_statusPage}">

		
		</td>
	</tr>	


</table>

</FORM>



  <FORM METHOD="post" ACTION="OrderServlet.do" >
   <input type="hidden" name="action" class="btnstyle" value="OrderByMmber">
   <input type="hidden" name="member_id"  value="<%=ordvo.getMember_id()%>">
  <input type="submit" value="返回" >
</FORM>
</body>
<script>
var a1;
var a2;
$('#send').click(function () {
	var a1=$(".city").val()
	var a2=$(".town").val()
	$("#address1").val(a1);
	$("#address2").val($(".town").val());
	
});


</script>

<script>

$("#zipcode3").twzipcode({
zipcodeIntoDistrict: true,
css: ["city form-control", "town form-control"],
countySel: "<%=(city==null)?"":city%>", // 指定城市 select name
districtSel: "<%=(town==null)?"":town%>" // 指定地區 select name

});

	

</script>

</body>
</html>

WebContent/back-end/shop_order/addDetailPage.jsp
<%@ page import="com.order_detail.model.Order_detailVO"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="java.util.*"%>
<%@ page import="com.product.model.*"%>
<%@ page import="com.ordermanager.shop.*"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%
	String order_no = (String) request.getAttribute("order_no");
	Order_detailVO order_detailvo = (Order_detailVO) request.getAttribute("detailvo");
	
	ProductService pSvc=new ProductService();
	List<ProductVO> productlist =pSvc.getAll();
%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>新增訂單明細品項</title>
</head>
<style>
.title {
	width: 350px;
	height: 100px;
	background-color: blue:
}
</style>
<body bgcolor='white'>
<FORM METHOD="post" ACTION="OrderServlet.do" >
<input type="submit" value="返回<%=order_no%>訂單明細">
 <input type="hidden" name="action" value="getorderdetail">
<input type="hidden" name="order_no" value="<%=order_no%>">
</FORM>


	<div class="title">
		<h3>
			訂單編號:<%=order_no%></h3>
	</div>

	<h3>商品新增:</h3>

	<%-- 錯誤表列 --%>
	<c:if test="${not empty errorMsgs}">
		<font style="color: red">請修正以下錯誤:</font>
		<ul>
			<c:forEach var="message" items="${errorMsgs}">
				<li style="color: red">${message}</li>
			</c:forEach>
		</ul>
	</c:if>

	<FORM METHOD="post" class="ui form" ACTION="detailServlet.do" name="form1">
		<table>
		<jsp:useBean id="productSvc" scope="page" class="com.product.model.ProductService" />
		<tr>
				<td>商品編號:</td>
				<td><select size="1" name="product_id">
			<c:forEach var="prodcutvo" items="${productSvc.all}">
				<option value="${prodcutvo.product_id}" 
				
				${(order_detailvo.product_id==deptVO.product_id)? 'selected':'' } >
				
				${prodcutvo.product_name}
			</c:forEach>
		</select></td>	
			</tr>
			<tr>
				<td>數量:</td>
				<td><input type="TEXT" name="quantity" size="45"
					value="<%=(order_detailvo == null) ? "" : order_detailvo.getQuantity()%>"
					placeholder="<%=(order_detailvo == null) ? "購買數量" : order_detailvo.getQuantity()%>" /></td>
			</tr>
			<tr>
				<td>單價:</td>
				<td><input type="TEXT" name="price" size="45"
					value="<%=(order_detailvo == null) ? "" : order_detailvo.getPrice()%>"
					placeholder="<%=(order_detailvo == null) ? "輸入單價 請勿輸入小數位或非數字" : order_detailvo.getPrice()%>" /></td>
			</tr>
		</table>
			
		<br>
		 <input type="hidden" name="action" value="sendaddDetail">
		<input type="hidden" name="order_no" value="<%=order_no%>">
		
		 <input type="submit" value="送出新增">
	</FORM>
</body>



</html>

WebContent/back-end/shop_order/order_manager_page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
    
<!DOCTYPE html>
<html>
<head>
<script src="<%=request.getContextPath()%>/css/DEMOJSPDEMO.css"></script>

<meta charset="BIG5">
<title>訂單管理頁面</title>
</head>
<body>
<style>
  table#title {
    
	width: 450px;
	background-color: #ffa0a5;
	margin-top: 5px;
	margin-bottom: 10px;
    border: 3px ridge Gray;
    height: 80px;
    text-align: center;
  }
  table#table-1 h4 {
    color: red;
    display: block;
    margin-bottom: 1px;
  }
  h4 {
    color: blue;
    display: inline;
  }
</style>

</head>
<body bgcolor='white'>

<table id="title">
   <tr><td><h3>訂單管理</h3><h4></h4></td></tr>
</table>


<h3>訂單查詢:</h3>
<%-- 錯誤表列 --%>
<c:if test="${not empty errorMsgs}">
	<font style="color:red">請修正以下錯誤:</font>
	<ul>
	    <c:forEach var="message" items="${errorMsgs}">
			<li style="color:red">${message}</li>
		</c:forEach>
	</ul>
</c:if><%-- 錯誤表列 --%>
<c:if test="${not empty errorMsgs}">
	<font style="color:red">請修正以下錯誤:</font>
	<ul>
	    <c:forEach var="message" items="${errorMsgs}">
			<li style="color:red">${message}</li>
		</c:forEach>
	</ul>
</c:if>
<!-------------->





<ul>
 <jsp:useBean id="ordSvc" scope="page" class="com.ordermanager.shop.OrderService" />
  <li><a href='listAllShopOrder.jsp'>所有訂單</a><br><br></li>
 
    <li>
     <FORM METHOD="post" ACTION="OrderServlet.do" >
       <b>選擇會員編號:</b>
       <select size="1" name="member_id">
         <c:forEach var="ordervom" items="${ordSvc.all}" > 
          <option value="${ordervom.member_id}">${ordervom.member_id}
         </c:forEach>   
       </select>
	  <input type="hidden" name="action" class="btnstyle" value="OrderByMmber">
	         <input type="submit" value="送出">
     </FORM>
  </li>
  
  
  
  
   
   <li>
     <FORM METHOD="post" ACTION="OrderServlet.do" >
       <b>選擇訂單編號:</b>
       <select size="1" name="order_no">
         <c:forEach var="ordervo" items="${ordSvc.all}" > 
          <option value="${ordervo.order_no}">${ordervo.order_no}
         </c:forEach>   
       </select>
	  <input type="hidden" name="action" class="btnstyle" value="getorderdetail">
	         <input type="submit" value="送出">
     </FORM>
  </li>












</ul>


<script>



</script>


</body>
</html>